import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import api from '../services/api';
import { socket } from '../services/socket';
import SeverityBadge from '../components/SeverityBadge';
import MitreBadge from '../components/MitreBadge';
import { ShieldAlert, Filter, Search, ArrowRight, RefreshCw } from 'lucide-react';

const AlertsPage = () => {
  const [alerts, setAlerts] = useState([]);
  const [detectionTypes, setDetectionTypes] = useState([]);
  const [severityFilter, setSeverityFilter] = useState('');
  const [statusFilter, setStatusFilter] = useState('');
  const [detectionFilter, setDetectionFilter] = useState('');
  const [searchIp, setSearchIp] = useState('');
  const [loading, setLoading] = useState(true);

  const fetchAlerts = async () => {
    setLoading(true);
    try {
      const res = await api.get('/alerts', {
        params: {
          severity: severityFilter || undefined,
          status: statusFilter || undefined,
          source_ip: searchIp || undefined,
          detection_rule: detectionFilter || undefined
        }
      });
      setAlerts(res.data.alerts);

      // Fetch detection types for filter dropdown
      try {
        const typesRes = await api.get('/alerts/detection-types');
        setDetectionTypes(typesRes.data.detection_types || []);
      } catch {}
    } catch (err) {
      console.error('Failed to fetch alerts:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAlerts();

    const handleNewAlert = (newAlert) => {
      setAlerts((prev) => [newAlert, ...prev]);
    };
    socket.on('new_alert', handleNewAlert);
    return () => socket.off('new_alert', handleNewAlert);
  }, [severityFilter, statusFilter, searchIp, detectionFilter]);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-100">Alerts Management</h1>
          <p className="text-xs text-slate-400">Security alert queue generated by detection rules and ML anomaly engines</p>
        </div>
        <button
          onClick={fetchAlerts}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-xs text-slate-300 transition-colors"
        >
          <RefreshCw className="w-3.5 h-3.5" />
          <span>Refresh Alerts</span>
        </button>
      </div>

      {/* Filter Tabs & Toolbar */}
      <div className="glass-panel rounded-xl p-4 flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-2">
          {['', 'NEW', 'INVESTIGATING', 'RESOLVED', 'FALSE_POSITIVE'].map((st) => (
            <button
              key={st}
              onClick={() => setStatusFilter(st)}
              className={`px-3 py-1.5 rounded-lg text-xs font-semibold uppercase tracking-wider transition-all ${
                statusFilter === st
                  ? 'bg-blue-600 text-white shadow-md shadow-blue-500/20'
                  : 'bg-slate-900 text-slate-400 hover:bg-slate-800 hover:text-slate-200'
              }`}
            >
              {st === '' ? 'All Statuses' : st.replace('_', ' ')}
            </button>
          ))}
        </div>

        <div className="flex items-center gap-3">
          <select
            value={severityFilter}
            onChange={(e) => setSeverityFilter(e.target.value)}
            className="bg-slate-900 border border-slate-700 rounded-lg px-3 py-1.5 text-xs text-slate-200 focus:outline-none"
          >
            <option value="">All Severities</option>
            <option value="CRITICAL">CRITICAL</option>
            <option value="HIGH">HIGH</option>
            <option value="MEDIUM">MEDIUM</option>
            <option value="LOW">LOW</option>
          </select>

          {detectionTypes.length > 0 && (
            <select
              value={detectionFilter}
              onChange={(e) => setDetectionFilter(e.target.value)}
              className="bg-slate-900 border border-slate-700 rounded-lg px-3 py-1.5 text-xs text-slate-200 focus:outline-none"
            >
              <option value="">All Detection Types</option>
              {detectionTypes.map((dt) => (
                <option key={dt.rule} value={dt.rule}>
                  {dt.rule.replace(/_/g, ' ')} ({dt.count})
                </option>
              ))}
            </select>
          )}

          <div className="relative">
            <Search className="w-3.5 h-3.5 text-slate-400 absolute left-3 top-2.5" />
            <input
              type="text"
              placeholder="IP Address..."
              value={searchIp}
              onChange={(e) => setSearchIp(e.target.value)}
              className="bg-slate-900 border border-slate-700 rounded-lg pl-8 pr-3 py-1.5 text-xs text-slate-200 focus:outline-none"
            />
          </div>
        </div>
      </div>

      {/* Alerts Table */}
      <div className="glass-panel rounded-xl p-5 overflow-x-auto">
        <table className="w-full text-left text-xs">
          <thead className="bg-slate-900 text-slate-400 uppercase font-mono tracking-wider border-b border-slate-800">
            <tr>
              <th className="p-3">Alert ID</th>
              <th className="p-3">Severity</th>
              <th className="p-3">Title & Description</th>
              <th className="p-3">Source IP</th>
              <th className="p-3">User</th>
              <th className="p-3">MITRE Technique</th>
              <th className="p-3">Risk Score</th>
              <th className="p-3">Assigned To</th>
              <th className="p-3">Status</th>
              <th className="p-3 text-right">Action</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-800/60 font-sans">
            {alerts.map((alert) => (
              <tr key={alert.id} className="hover:bg-slate-800/40 transition-colors">
                <td className="p-3 font-mono font-semibold text-slate-300">ALT-{alert.id}</td>
                <td className="p-3"><SeverityBadge severity={alert.severity} /></td>
                <td className="p-3 max-w-sm">
                  <div className="font-semibold text-slate-200">{alert.title}</div>
                  <div className="text-[11px] text-slate-400 line-clamp-1">{alert.description}</div>
                  {alert.risk_factors?.detection_rule && (
                    <span className="mt-1 inline-block px-1.5 py-0.5 rounded bg-cyan-500/10 border border-cyan-500/30 text-[9px] font-mono font-bold text-cyan-400 uppercase">
                      {alert.risk_factors.detection_rule.replace(/_/g, ' ')}
                    </span>
                  )}
                </td>
                <td className="p-3 font-mono text-slate-300">{alert.source_ip}</td>
                <td className="p-3 text-slate-300">{alert.username || 'N/A'}</td>
                <td className="p-3"><MitreBadge techniqueId={alert.mitre_technique_id} /></td>
                <td className="p-3 font-mono font-bold text-amber-400">{alert.risk_score}</td>
                <td className="p-3 text-slate-300">{alert.assigned_to || 'Unassigned'}</td>
                <td className="p-3">
                  <span className="px-2 py-0.5 rounded text-[10px] uppercase font-semibold bg-slate-800 border border-slate-700 text-slate-300">
                    {alert.status}
                  </span>
                </td>
                <td className="p-3 text-right">
                  <Link
                    to={`/alerts/${alert.id}`}
                    className="inline-flex items-center gap-1 text-blue-400 hover:text-blue-300 font-semibold"
                  >
                    Details <ArrowRight className="w-3.5 h-3.5" />
                  </Link>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default AlertsPage;
